apiVersion: v1
kind: Service
metadata:
  name: discount-service
spec:
  selector:
    app: discount-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount-service
  template:
    metadata:
      labels:
        app: discount-service
    spec:
      containers:
        - name: discount-service
          image: discount-service:latest
          ports:
            - containerPort: 8080