apiVersion: v1
kind: ConfigMap
metadata:
  name: discount-service
data:
  # kv format
  key: "value"
  actualConfigFile: "name.properties"

  # file format
  name.properties: |
    field=value1,value2
