apiVersion: v1
kind: Service
metadata:
  name: travel-service
spec:
  selector:
    app: travel-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-service
  template:
    metadata:
      labels:
        app: travel-service
    spec:
      containers:
        - name: travel-service
          image: travel-service:latest
          ports:
            - containerPort: 8080